# goバージョン
FROM golang:1.22.1

Run go install -v golang.org/x/tools/gopls@latest
Run go install -v golang.org/x/tools/cmd/goimports@latest
Run go install github.com/onsi/ginkgo/v2/ginkgo@v2.20.0
Run go install github.com/air-verse/air@latest

WORKDIR /src